/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "sys_clocks.h"
#include "led.h"
#include "software_timers.h"

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

SoftTimer_t TimerLD2;

void TaskLD2(void);

int main(void)
{
	SystemClockHSI16();

	LED_LD2_Init();

	SoftTimerAction(&TimerLD2, TaskLD2);
	SoftTimerStart(&TimerLD2, 500);

    /* Loop forever */
	while(1)
	{

		SoftTimerEvent(&TimerLD2);

	}
}

void TaskLD2(void)
{
	LED_LD2_Toggle();
}
